color0 #17130e
color1 #ffb4ab
color2 #ffb86b
color3 #e0c1a3
color4 #becc9b
color5 #ffb86b
color6 #e0c1a3
color7 #ebe1d9
color8 #9d8e81
color9 #ffb4ab
color10 #ffb86b
color11 #e0c1a3
color12 #becc9b
color13 #ffb86b
color14 #e0c1a3
color15 #ebe1d9

cursor                #ebe1d9
cursor_text_color     #17130e
background            #17130e
foreground            #ebe1d9
selection_foreground  #d5c4b5
selection_background  #50453a
active_border_color   #ffb86b
inactive_border_color #50453a
url_color             #ffb86b

active_tab_foreground   #492900
active_tab_background   #ffb86b
inactive_tab_foreground #d5c4b5
inactive_tab_background #50453a
cursor_trail_color      #d5c4b5
